name: Semver
description: Upgrades the version tag as per semver.

inputs:
  github-token:
    description: GitHub token.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    # Setting up pnpm.
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        pnpm add --global semantic-release @semantic-release/changelog @semantic-release/git
        pnpm dlx semantic-release --branches main --plugins \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/changelog \
          @semantic-release/github \
          @semantic-release/git
      shell: bash
